name: preview-close
on:
  pull_request:
    branches:
      - main
    types:
      - closed
      - converted_to_draft
concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true
jobs:
  preview-close:
    name: Close preview
    runs-on: ubuntu-latest
    steps:
      - name: Delete Preview Branch
        uses: neondatabase/delete-branch-action@v3.2.0
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch: |-
            preview/pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}
